couch_it/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('movies.urls')),
    path('admin/', admin.site.urls),
]

movies/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>', views.single_movie, name="single_movie"),
    path('show/<int:tv_id>', views.single_show, name="single_show"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

movies/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    """
    class facilitates the creation of profile objects
    """
    username = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="images", null=True)

movies/views.py
from django.shortcuts import render
import tmdbsimple as tmdb
from decouple import config
from googleapiclient.discovery import build


# Create your views here.
tmdb.API_KEY=config('API_KEY')
API_KEY=config('DEVELOPER_KEY')


def index(request):
    """
    view function returns template that displays popular and upcoming movies
    """
    popular_movies_tmdb = tmdb.Movies('popular')
    popular_movies = popular_movies_tmdb.info()['results']

    upcoming_movies_tmdb = tmdb.Movies('upcoming')
    upcoming_movies = upcoming_movies_tmdb.info()['results']

    popular_shows_tmdb = tmdb.TV('popular')
    popular_shows = popular_shows_tmdb.info()['results']

    current_shows_tmdb = tmdb.TV('airing_today')
    current_shows = current_shows_tmdb.info()['results']

    top_shows_tmdb = tmdb.TV('top_rated')
    top_shows = top_shows_tmdb.info()['results']

    return render(request, 'movies.html', {"popular":popular_movies, 'upcoming':upcoming_movies, 'shows':popular_shows, "current":current_shows, 'top':top_shows})

def single_movie(request, movie_id):
    """
    view function renders template that displays the details of a single movie
    """
    movie = tmdb.Movies(movie_id)
    movie = movie.info()
    youtube = build('youtube', 'v3', developerKey=API_KEY)
    movie_name = movie['original_title']
    req = youtube.search().list(q=movie_name, part='snippet', type='video', maxResults=1)
    res = req.execute()
    for result in res.get('items'):
        if result['id']['kind'] == 'youtube#video':
            video_id = result['id']['videoId']
    return render(request, 'single_movie.html', {'movie':movie, 'videoId':video_id})

def single_show(request, tv_id):
    """
    view function renders template that displays the details of a single TV show
    """
    show = tmdb.TV(tv_id)
    show = show.info()
    youtube = build('youtube', 'v3', developerKey=API_KEY)
    show_name = show['original_name']
    req = youtube.search().list(q=show_name, part="snippet", type='video', maxResults=1)
    res = req.execute()
    for result in res.get('items'):
        if result['id']['kind'] == 'youtube#video':
            video_id = result['id']['videoId']
    return render(request, 'single_show.html', {"show":show, 'videoId':video_id})

movies/templates/movies.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Movies</title>
        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'movies/index.css'%}">
        {% endblock %}
        <script src="https://kit.fontawesome.com/79cafd0f3e.js" crossorigin="anonymous"></script>
    </head>
    <body>
       
        <div class="jumbotron" style="background-color: black; color: white;">
            <h1 id="title"><a style="color: red;" href="{% url 'movies:index' %}">Couch_It</a></h1>
        </div>
        <h2>Popular Movies</h2>
        <div class="container-fluid">
            {% for movie in popular %}
                <a href="{% url 'movies:single_movie' movie.id %}" class="item"><img class="img-responsive" src="https://image.tmdb.org/t/p/w342/{{movie.poster_path}}"></a> 
            {% endfor %}
        </div>
        <h2>Upcoming Movies</h2>
        <div class="container-fluid">
            {% for movie in upcoming %}
                <a href="{% url 'movies:single_movie' movie.id %}" class="item"><img class="img-responsive" src="https://image.tmdb.org/t/p/w342/{{movie.poster_path}}"></a> 
            {% endfor %}
        </div>
        <h2>Popular TV Shows</h2>
        <div class="container-fluid">
            {% for show in shows %}
                <a href="{% url 'movies:single_show' show.id %}" class="item"><img class="img-responsive" src="https://image.tmdb.org/t/p/w342/{{show.poster_path}}"></a> 
            {% endfor %}
        </div>
        <h2>Current Shows</h2>
        <div class="container-fluid">
            {% for show in current %}
                <a href="{% url 'movies:single_show' show.id %}" class="item"><img class="img-responsive" src="https://image.tmdb.org/t/p/w342/{{show.poster_path}}"></a> 
            {% endfor %}
        </div>
        <h2>Top Rated Shows</h2>
        <div class="container-fluid">
            {% for show in top %}
                <a href="{% url 'movies:single_show' show.id %}" class="item"><img class="img-responsive" src="https://image.tmdb.org/t/p/w342/{{show.poster_path}}"></a> 
            {% endfor %}
        </div>
        {% block scripts %}
            <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
            {% bootstrap_javascript %}
        {% endblock %}
    </body>
</html>

movies/templates/navbar.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1">
        <script src="https://kit.fontawesome.com/79cafd0f3e.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-black fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'movies:index' %}">Couch_It<i class="fa fa-home"></i></a>
                </div>
            </div>
            
        </nav>
    </body>
</html>

movies/templates/single_movie.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{title}}</title>
        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'movies/index.css'%}">
        {% endblock %}
    </head>
    <body>
        
        <div class="jumbotron" style="background-color: black;">
            <h1 id="title"><a style="color: red;" href="{% url 'movies:index' %}">Couch_It</a></h1>
            <div class="embed-responsive embed-responsive-21by9">
                <iframe class="embed-responsive-item" id="video" src="//www.youtube.com/embed/{{videoId}}?rel=0" frameborder="0"></iframe>
            </div>
        </div>
        <div class="container-fluid" id="movie-detail">
            <div class="row">
                <div class="col-md-6">
                    <h1>{{movie.title}}</h1>
                    <p>Score: {{movie.vote_average}}</br>Release Date: {{movie.release_date}}</p>
                    <p>{{movie.overview}}</p>
                </div>
                <div class="col-md-6">
                    <img class="img-responsive" src="https://image.tmdb.org/t/p/w342/{{movie.poster_path}}">
                </div>
            </div>
            
        </div>
    </body>

</html>

movies/templates/single_show.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{title}}</title>
        {% block styles %}
            {% bootstrap_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'movies/index.css'%}">
        {% endblock %}
    </head>
    <body>
        <div class="jumbotron" style="background-color: black;">
            <h1 id="title"><a style="color: red;" href="{% url 'movies:index' %}">Couch_It</a></h1>
            <div class="embed-responsive embed-responsive-21by9">
                <iframe  class="embed-responsive-item" id="video" src="//www.youtube.com/embed/{{videoId}}?rel=0" frameborder="0"></iframe>
            </div>
            
        </div>
        <div class="container-fluid" id="movie-detail">
            <div class="row">
                <div class="col-md-6">
                    <h1>{{show.name}}</h1>
                    <p style="display: inline-block;">Score: {{show.vote_average}}<br>First Aired: {{show.first_air_date}}</br>Seasons: {{show.number_of_seasons}}</br>Runtime: {{show.episode_run_time}} minutes</p>
                    <p>{{show.overview}}</p>
                </div>
                <div class="col-md-6">
                    <img class="img-responsive" src="https://image.tmdb.org/t/p/w342/{{show.poster_path}}">
                </div>
            </div>
            
        </div>
    </body>

</html>